#! /bin/bash

set -euo pipefail

cd "$(dirname "$0")"
cd ..

./build.py -j4
./fast-downward.py --search -- --search-options --help --json

# blind
# cegar
# hm
# hmax
# merge_and_shrink
# operatorcounting
# pdb
# combo
# genetic
# hillclimbing
# systematic
# exact
# original
# lmcut_constraints
# pho_constraints
# state_equation_constraints
# merge_dfp
# merge_linear
# shrink_bisimulation
# shrink_fh
# shrink_random
# ordered_systematic
# unsolvable_all_states_potential
# stubborn_sets_ec, stubborn_sets_simple, null
# deadpdbs
# feature_constraints
# unsolvable_search
# deadpdbs_simple
