release = ["-DCMAKE_BUILD_TYPE=Release"]
debug = ["-DCMAKE_BUILD_TYPE=Debug"]
# USE_GLIBCXX_DEBUG is not compatible with USE_LP (see issue983).
glibcxx_debug = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO", "-DUSE_GLIBCXX_DEBUG=YES"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES"]

# Aidos 1 and 2 can use this minimal build. Aidos 3 needs "release".
aidos = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DDISABLE_PLUGINS_BY_DEFAULT=YES",
    "-DPLUGIN_CEGAR_ENABLED=YES",
    "-DPLUGIN_EAGER_SEARCH_ENABLED=YES",
    "-DPLUGIN_IPC_MAX_HEURISTIC_ENABLED=YES",
    "-DPLUGIN_LANDMARK_CUT_HEURISTIC_ENABLED=YES",
    "-DPLUGIN_OPERATOR_COUNTING_ENABLED=YES",
    "-DPLUGIN_PDBS_ENABLED=YES",
    "-DPLUGIN_StubbornSetsEC_ENABLED=YES",
    "-DPLUGIN_UNSOLVABLE_SEARCH_ENABLED=YES",
]

DEFAULT = "release"
DEBUG = "debug"
